# Generated by Django 4.2.28 on 2026-02-16 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person', max_length=200)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('subject', models.CharField(blank=True, help_text='Subject of the message', max_length=300)),
                ('message', models.TextField(help_text='Message content')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the message was received')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the message has been read')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
